# 配置文件
# 数据库名称 mysql,postgresql
db_name: postgres

# 是否开启dug模式打印sql true,false
is_print_sql: true

# 是否开启debug模式 true,false
is_debug: true

server_port: 8080

# mysql 配置
mysql_dirverName: mysql
mysql_host: 127.0.0.1
mysql_port: 3306
mysql_database: gin_zc
mysql_username: root
mysql_password: 123456
mysql_charset: utf8

# postgresql 配置
postgres_dirverName: postgresql
postgres_host: 127.0.0.1
postgres_port: 5432
postgres_database: gin_zc
postgres_username: postgres
postgres_password: 123456
postgres_charset: utf8
