# 配置文件
# 数据库名称 mysql,postgresql
db_name: postgres

# 是否开启dug模式打印sql true,false
is_print_sql: true

# 是否开启debug模式 true,false
is_debug: true

server_port: 8080

# JWT 配置
jwt:
  # JWT 密钥，生产环境请使用环境变量设置
  secret: "your-super-secret-jwt-key-change-this-in-production"
  # Token 过期时间（小时）
  expire_hours: 168
  # Token 签发者
  issuer: "gin-template"

# mysql 配置
mysql_dirverName: mysql
mysql_host: 127.0.0.1
mysql_port: 3306
mysql_database: gin_zc
mysql_username: root
mysql_password: 123456
mysql_charset: utf8

# postgresql 配置
postgres_dirverName: postgresql
postgres_host: code.theing.cc
postgres_port: 5414
postgres_database: gin_zc
postgres_username: admin
postgres_password: 12357890
postgres_charset: utf8
